### ISSUE TITLE
Deployment Guide locations

### ISSUE THREAD

**Issue by robinmalik** [PaloAltoNetworks/ReferenceArchitectures#3]
Hi,

Where can we find the referenced: "February 2019 (current) deployment guides" ? I've only been able to find "https://www.paloaltonetworks.com/resources/whitepapers/azure-deployment-guide-shared-resource" but this is specified as 2018 as per the README.md.

Thanks,

Robin

**Comment by agroudan** [comment]
The February 2019 guides are complete, but have not yet been posted to the public Palo Alto Networks website (in-progress).

I will add links to the README when the posting is complete.

If you like, I can provide you copies of the guides as an interim workaround.

Please email me directly agroudan@paloaltonetworks.com

**Comment by robinmalik** [comment]
Thanks @agroudan, I'll drop you an email in the morning!

**Comment by agroudan** [comment]
Docs are now posted to Palo Alto Networks website. Links have been added to the README.
